<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BDC6-DX-6BWDNK2" ignored="1" name="Test" tests="6" failures="1" timestamp="2019-09-17T15:35:28 IST" time="0.085" errors="0">
  <testcase name="f" time="0.005" classname="selenium_day3.testNG_demo1"/>
  <testcase name="f1" time="0.002" classname="selenium_day3.testNG_demo1"/>
  <testcase name="Register" time="0.002" classname="selenium_day3.NewTest"/>
  <testcase name="Logout" time="0.003" classname="selenium_day3.NewTest"/>
  <testcase name="testMethod1" time="0.008" classname="selenium_day3.testNG_demo3">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [11] but found [10]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [11] but found [10]
at selenium_day3.testNG_demo3.testMethod1(testNG_demo3.java:20)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod2" time="0.002" classname="selenium_day3.testNG_demo3"/>
  <testcase name="Login" time="0.0" classname="selenium_day3.NewTest">
    <ignored/>
  </testcase> <!-- Login -->
</testsuite> <!-- Test -->
